### ISSUE TITLE
Method $vuety-provide conflicts with existing Vue instance method

### ISSUE THREAD

**Issue by BOTPaul** [strantr/vuety#20]
Seems this function in newer versions of Vue is picked up as an issue.

In the provide function in bundle.js adding `delete v.proto["$vuety-provide"]` appears to resolve this issue, although I'm unsure as to why.

``` ts
v.done(function (data) {
  delete v.proto["$vuety-provide"];
  data.options.provide = function () {
    var _this = this;
    var provide = {};
    Object.keys(provided).forEach(function (k) { return provide[k] = _this[provided[k]]; });
      return provide;
    };
});
```

**Comment by strantr** [comment]
961bc2fb60e567233e6fcf056d550f480bb461ab
